export const enum Colors {
  blueD = 'blueD',
  blueMD = 'blueMD',
  blueM = 'blueM',
  blueML = 'blueML',
  blueL = 'blueL',
  pinkD = 'pinkD',
  pinkMD = 'pinkMD',
  pinkM = 'pinkM',
  pinkML = 'pinkML',
  pinkL = 'pinkL',
  blackD = 'blackD',
  blackM = 'blackM',
  blackML = 'blackML',
  blackL = 'blackL',
  white = 'white',
  grayL = 'grayL',
  grayML = 'grayML',
  grayM = 'grayM',
  grayD = 'grayD',
  error = 'error',
  warning = 'warning',
  success = 'success'
}
